USE ROLE IDENTIFIER($IROP_GNN_RISK_ROLE);

CREATE DATABASE IF NOT EXISTS IDENTIFIER($IROP_GNN_RISK_DB);
DROP SCHEMA IF EXISTS IDENTIFIER($IROP_GNN_RISK_DB || '.PUBLIC');

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($IROP_GNN_RISK_DB || '.RAW');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($IROP_GNN_RISK_DB || '.ATOMIC');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($IROP_GNN_RISK_DB || '.ML_PROCESSING');
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($IROP_GNN_RISK_DB || '.IROP_MART');

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($IROP_GNN_RISK_WH)
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE STAGE IF NOT EXISTS IDENTIFIER($IROP_GNN_RISK_DB || '.RAW.IROP_GNN_RISK_STAGE')
    DIRECTORY = (ENABLE = TRUE);

GRANT USAGE ON DATABASE IDENTIFIER($IROP_GNN_RISK_DB) TO ROLE IDENTIFIER($IROP_GNN_RISK_ROLE);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($IROP_GNN_RISK_DB) TO ROLE IDENTIFIER($IROP_GNN_RISK_ROLE);
GRANT ALL ON ALL SCHEMAS IN DATABASE IDENTIFIER($IROP_GNN_RISK_DB) TO ROLE IDENTIFIER($IROP_GNN_RISK_ROLE);
GRANT USAGE ON WAREHOUSE IDENTIFIER($IROP_GNN_RISK_WH) TO ROLE IDENTIFIER($IROP_GNN_RISK_ROLE);
